// <auto-generated />
using System;
using EraSnap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EraSnap.Data.Migrations
{
    [DbContext(typeof(EraSnapDbContext))]
    [Migration("20240224201351_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EraSnap.Data.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("EraSnap.Data.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExampleImagePath")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("UserPrompt")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Prompt");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecfe5afa-ed76-4472-b38d-5ba2e0fe5591"),
                            ExampleImagePath = "ecfe5afa-ed76-4472-b38d-5ba2e0fe5591_image.jpg",
                            Name = "Prompt 1",
                            Text = "test prompt",
                            UserPrompt = false
                        },
                        new
                        {
                            Id = new Guid("bf16162b-279a-40a5-b3ca-bed7748e68e5"),
                            ExampleImagePath = "bf16162b-279a-40a5-b3ca-bed7748e68e5_image.jpg",
                            Name = "Prompt 2",
                            Text = "test prompt",
                            UserPrompt = false
                        },
                        new
                        {
                            Id = new Guid("0b2942ec-93ac-4c23-be54-1389ed3a0c6e"),
                            ExampleImagePath = "0b2942ec-93ac-4c23-be54-1389ed3a0c6e_image.jpg",
                            Name = "Prompt 3",
                            Text = "test prompt",
                            UserPrompt = false
                        });
                });

            modelBuilder.Entity("EraSnap.Data.Entities.Image", b =>
                {
                    b.HasOne("EraSnap.Data.Entities.Prompt", "Prompt")
                        .WithMany("Images")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("EraSnap.Data.Entities.Prompt", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
